# Generated by Django 5.2.6 on 2025-09-11 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userentries', '0006_playbook_trade_database'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.CharField(max_length=50)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss')], max_length=4)),
                ('realized_r', models.DecimalField(decimal_places=2, help_text='Rzeczywisty wynik w R, np. 2.5 lub -1', max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_trade_logs', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_logs', to='userentries.playbook')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
