# Generated by Django 5.2.6 on 2025-09-05 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, null=True)),
                ('trade_type', models.CharField(choices=[('daytrading', 'Day Trading'), ('scalping', 'Scalping'), ('swing', 'Swing')], default='daytrading', max_length=20, verbose_name='trade type choice')),
                ('entry_criteria', models.JSONField(default=list)),
                ('exit_strategy', models.JSONField(default=list)),
                ('sl_rules', models.JSONField(default=list)),
                ('confluence', models.JSONField(default=list)),
                ('trade_management', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
