# Generated by Django 5.2.6 on 2025-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='checklist',
            field=models.JSONField(default=list),
        ),
    ]
