# Generated by Django 5.2.6 on 2025-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentries', '0002_playbook_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='trade_type',
            field=models.CharField(choices=[('day_trading', 'Day Trading'), ('scalping', 'Scalping'), ('swing_trading', 'Swing')], default='daytrading', max_length=20, verbose_name='trade type choice'),
        ),
    ]
