# Generated by Django 5.2.6 on 2025-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentries', '0003_alter_playbook_trade_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='category',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='playbook',
            name='trade_type',
            field=models.CharField(choices=[('day_trading', 'Day Trading'), ('scalping', 'Scalping'), ('swing_trading', 'Swing')], default='day_trading', max_length=20, verbose_name='trade type choice'),
        ),
    ]
