# Generated by Django 5.2.6 on 2025-09-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userentries', '0004_rename_category_playbook_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='confluence',
            new_name='enhancers',
        ),
        migrations.RenameField(
            model_name='playbook',
            old_name='sl_rules',
            new_name='stop_loss_rules',
        ),
    ]
