# Generated by Django 5.2.6 on 2025-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentries', '0005_rename_confluence_playbook_enhancers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='trade_database',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
