# Generated by Django 5.2.6 on 2025-09-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userentries', '0006_playbook_trade_database'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbook',
            options={'ordering': ['-title']},
        ),
    ]
