# Generated by Django 5.2.6 on 2025-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marketbias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbias',
            name='bias',
            field=models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral'), ('RANGE', 'Range'), ('RESURRECTION', 'Resurrection')], default='NEUTRAL', max_length=20),
        ),
    ]
