# Generated by Django 5.2.6 on 2025-09-07 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userentries', '0006_playbook_trade_database'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Sample', max_length=200)),
                ('size', models.PositiveIntegerField(default=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('instrument', models.CharField(max_length=50)),
                ('initial_risk_pips', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('initial_target_pips', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('realized_r_multiple', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Breakeven')], max_length=4)),
                ('rules_followed', models.BooleanField(default=True)),
                ('context', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='userentries.playbook')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade_samples.tradesample')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
