# Generated by Django 5.2.6 on 2025-09-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradesample',
            options={'ordering': ['-start_date']},
        ),
    ]
