# Generated by Django 5.2.6 on 2025-09-07 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='C', max_length=2)),
                ('goal', models.TextField(blank=True)),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reminders', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('mistakes_with_solutions', models.JSONField(blank=True, default=list)),
                ('performance_table', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('owner', 'date')},
            },
        ),
    ]
