# Generated by Django 5.2.6 on 2025-09-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportcard',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('N/A', 'N/A')], default='C', max_length=3),
        ),
    ]
